defaults: &defaults
  # adapter: mysql2
  # encoding: utf8
  # host: yamysql-pub.c5uthvjn4chs.ap-northeast-1.rds.amazonaws.com
  # reconnect: false
  # database: hp2014
  # username: root
  # password: 003tk333
  adapter: postgresql
  encoding: unicode
  host: yamgresql.c5uthvjn4chs.ap-northeast-1.rds.amazonaws.com
  pool: 5
  port: 5432
  reconnect: false
  database: yamaokaya
  username: root
  password: 003tk333

development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
